### ISSUE TITLE
Creator and Shared-with user switched

### ISSUE THREAD

**Issue by jamesholston** [socialappslab/appcivist#102]
Two proposals were created by João Albert Arantes do Amaral and shared with James Holston and others.  They used to be visible to James Holston via the filter "Compartilhadas Comigo."  They are no longer visible there.  Instead, they now appear under the filter "Minhas Propostas" and show that they were created by James Holston and shared with João Alberto Arantes do Amaral.  Somehow these roles were switched???  This assignment is incorrect and we need to revert them to their original roles.  Has this kind of switch happened with other proposals?

![screen shot 2018-06-23 at 12 04 33 am](https://user-images.githubusercontent.com/5572598/41805232-1ac52410-767c-11e8-92bf-0701dd33fc7e.png)

![screen shot 2018-06-23 at 12 05 37 am](https://user-images.githubusercontent.com/5572598/41805235-34954c44-767c-11e8-9460-99c998c3bb6c.png)

**Comment by cdparra** [comment]
While doing maitainance work, cleaning up proposals without creators, I may have switched some. I found 2 proposals by the users mentioned in this issue. I have switched back both. Perhaps would be good to ask around if anyone else has experienced something similar. 

There are 53 proposals with more than one author (i.e., 1 creator + 1 or more shared with). I doubt they have been all affected, but they could potentially have been. Since there is no real difference in terms of access, this is not blocking anything, but would be good to check. The 53 proposals collectively are associated with 45 unifesp users. I will send out the list of emails to @jameholston and then the UNIFESP team craft an email asking this users to check their proposals, just in case.
