### ISSUE TITLE
 Logout from profile page continues goes to incorrect URL

### ISSUE THREAD

**Issue by jamesholston** [socialappslab/appcivist#103]
Logout from profile page continues goes to incorrect URL.
  
![screen shot 2018-06-23 at 12 31 25 am](https://user-images.githubusercontent.com/5572598/41805262-c9913876-767c-11e8-8285-d98d57f1fc4a.png)

**Comment by cdparra** [comment]
This is not really a bug, but a feature: signing out always reload the same page in public form. Since there is no public profile, it loads a page with empty fields. 

I moved this to [socialappslab/appcivist-pb-client#1249
Signing out from profile page should redirect to last page visited before that](https://github.com/socialappslab/appcivist-pb-client/issues/1249). The new feature is to redirect to the last page visited before the profile.
