### ISSUE TITLE
Prevent non-logged in viewers from accessing proposal page

### ISSUE THREAD

**Issue by jamesholston** [socialappslab/appcivist#121]
Currently non-logged in viewers can access, comment, and edit a proposal by clicking on its card.  This is completely wrong.  Only members of the Unifesp community can access the content of a proposal and comment on it (in Public Draft and Published Proposal).  Only those shared with a Public Draft can edit it.  

Non-logged in viewers can see the campaign page and therefore the public cards.  But they should not be able to enter them.  

Therefore, (1) prevent non-logged in viewers from accessing proposal page from the card.  (2) If a non-logged in viewer tries to access a card, present the following error message:  
"Para acessar esta proposta, faça login."

Note in the screenshot that I am not logged in and yet have accessed the proposal:

![screen shot 2018-07-04 at 9 20 46 am](https://user-images.githubusercontent.com/5572598/42277099-9285bd5e-7f6c-11e8-8bd2-4ffcfa9ab01d.png)

**Comment by cdparra** [comment]
@jamesholston I don't think this is possible. If we don't want people to access a proposal page, it should not appear in the campaign page. As per request from UNIFESP, we make both PUBLISHED and PUBLIC_DRAFT proposals visible and counted in the number of `Public` proposals. Do you want us to rollback this change?

**Comment by cdparra** [comment]
I also removed the label `bug` because this is not a bug, this is a feature we implemented as per your request, for the UNIFESP initiative.

**Comment by cdparra** [comment]
A one more comment: as of current PEERDOC implementation, if you have previously created a proposal and therefore signed in into PEERDOC, you will be able to edit any peerdoc you have access to. Until permissions are done on PD, the only think appcivist can do is hide the embedded peerdoc, but that would be inconsistent in the logic since we are saying that the proposal is a PUBLIC DRAFT, so why cant' I see it if it is PUBLIC?
