### ISSUE TITLE
Change Campaign Page login button to "Fazer Login"

### ISSUE THREAD

**Issue by jamesholston** [socialappslab/appcivist#125]
--  Change “Iniciar Sessão” button  to  =>  "Fazer Login"
Leave where it is currently.

[[[-- Move the Fazer Login button to middle of blue nav bar between Mídia and Desenvolvido.  
-- Use white box, green button, white letters (like email verification).  
-- It should be obvious but contained and not overwhelming. And not floating but fixed on blue nav bar.]]]

**Comment by cdparra** [comment]
Is this really necessary? @jamesholston

Are there actually people not finding the sign in link where it is now, which is a very standard placement? 

If there is really a necessity for this, perhaps a better solution would be to simply have an horizontal message below or before the description of the phase, otherwise the section where the prompts are risks becoming overloaded.

If it is not a necessity, I prefer to work on the backlog issues.

**Comment by jamesholston** [comment]
It is necessary.  It is surprising how many people do not know what to do when they get to the campaign page.  There is a lot of information on it and they get lost.  Therefore we want to link the new description which says "Faça login" with the new login button "Fazer Login" which needs to be really obvious.  I don't think it will overload the prompts section because it will be an obvious overlay and because it will only appear on the non logged in screen.  People here prefer it where I described it to your suggestion of putting it more discretely below or above the phase description -- which they feel will overload that part of the screen and not be an obvious overlay but compete with the Criar Proposta button.

**Comment by cdparra** [comment]
If we add a modal window, we will eventually have problems like the ones we have with the motivational prompts. For example, in campaigns where you have working groups, the toolbar will contain also a link for Working Groups, and then the "Fazer Login" modal window will start hiding one of the elements. Even as is now, with smaller width browser windows, the there will be a problem of elements getting all on top of each other. 

So, what the real problem is here? Do we simply need to make the "Sign in" link in the right top corner of the page more visible? Maybe it is enough to turn that into a button? 

I don't really like this change. I think we will be introducing a problem more than a solution. 

Another option is to include a button to login, large and visible, after the description of the campaign. Something as the one below, where you have a "Registrarse" in the top-right corner, emphasized as a button, and then a "Conocé las propuestas creadas" as another big button that could also lead to the same login window.  

![image.png](https://images.zenhubusercontent.com/55ca3bba4f7a08fbb7f43c8a/da2ee332-334e-4a1a-ba72-54890a318bfa)

**Comment by cdparra** [comment]
To sum up, the only thing to do is the first item in the description

**Comment by jamesholston** [comment]
Agreed:  Leave button where it is and just change to "Fazer Login"
