### ISSUE TITLE
Prevent non-authors from changing the custom fields of a Public Draft

### ISSUE THREAD

**Issue by jamesholston** [socialappslab/appcivist#126]
Currently, logged in users who are NOT authors of a Public Draft can change its custom fields:  theme, keywords, campus proposta, and summary.  This should not be allowed.  This would seem to be an AppCivist issue, independent of PeerDoc permissions.

Once we have them, PeerDoc permissions will prevent non-authors from editing the PD proposal text, though they can comment on it.

**Comment by cdparra** [comment]
I couldn't reproduce this. Can you provide some details about which proposals you accessed, with what users, and who was the creator, and who was in the list of shared with. 

Are you sure the user you used was not in the list of shared with? Because if it was, then it is allowed to change all those things. 
![image](https://user-images.githubusercontent.com/630150/42605443-f636ff82-8545-11e8-814b-f1fec63a1502.png)

**Comment by cdparra** [comment]
Also: make sure the user is not a COORDINATOR. Coordinators also have full access to all proposals.

**Comment by jamesholston** [comment]
You can close this issue.  I was testing it as a coordinator, forgetting that coordinators have full powers to edit the custom and regular fields.  I tested again using a non-coordinator, and could not edit any of these fields.  So, behavior is correct.
