### ISSUE TITLE
Status definition banner to cover proposal text when logged out

### ISSUE THREAD

**Issue by jamesholston** [socialappslab/appcivist#127]
Make the status definition banner -- "Esta proposta tem o status de Rascunho Público. Toda a comunidade..." -- cover and block from view the proposal text (PD) of PUBLIC DRAFTS when logged out. This cover will also make it impossible for non-community members (those who cannot login) to comment.

The screen shot below shows a logged-in view with the status definition banner below the proposal text.  This is good as it informs the status but does not prevent viewing or commenting on it. 

![screen shot 2018-07-11 at 9 41 07 pm](https://user-images.githubusercontent.com/5572598/42606388-b0987c68-8553-11e8-8018-55674c76c78c.png)

The next screen shot below shows a logged-out view.  My suggestion is to move the banner up to cover the PD proposal text.

![screen shot 2018-07-11 at 9 46 19 pm](https://user-images.githubusercontent.com/5572598/42606483-4a0c9a1e-8554-11e8-91d0-946313f1fbd9.png)

**Comment by cdparra** [comment]
@jamesholston the idea of that banner was to be visible only when the PD is not visible. One of the issues will fix the situation that we have now, where the banner is visible even when the PD is there. 

Now, you are asking to keep it anyways, when the proposal is in the PUBLIC_DRAFT status. There are two problems with this: 
1. If the proposal text is long, it will be at the end of the page and you will have to scroll to see it, which somehow does not play well with the goal of informing the participant about the status. 
2. The way it is designed, it takes up a lot of space, and it is like that because we want to fill in the void left by an non visible PD. If we keep it like this when the PD is visible, it becomes too big and even more prominent than the proposal it self. 

I suggest we instead follow one of the following strategies: 
1. Display this explanation when hovering over the status (on the toolbar) or clicking on it, or clicking on a question mark on the side of the status. 
2. Display the message as is, but before the PD text and with a format that makes it less prominent, something like the alerts below might be enough: 
![image](https://user-images.githubusercontent.com/630150/42646061-c2773e90-85cd-11e8-9177-8297d1c996da.png)

what do you think?

**Comment by jamesholston** [comment]
Please see my recent Slack comments on the PeerDoc channel.  I may have to talk about this issue on Hangout to reach a decision.  

The key question is visibility of Public Drafts for non-logged-in users.  It seems to me that we can use the same protocol we have for Private Drafts for non-logged-in users v logged-in users.

Below are two examples of the same Private Draft that is very long (several "pages"), the first for logged-in users and the second for non-logged-in users.

(1) Private Draft view for logged-in user, showing the full PD text.  There is no explanatory message (but we can talk about where we might put one later -- or not put one at all for logged-in users): 

![screen shot 2018-07-12 at 8 12 44 pm](https://user-images.githubusercontent.com/5572598/42664344-a6aef3d6-8610-11e8-9f8d-b1902f443fa6.png)

(2)  Private Draft view of the same proposal for non-logged-in user.  Banner hides the PD text, but the AppCivist fields are still visible (which is what Unifesp wants).  This is the solution I propose for the non-logged-in view of Public Drafts:

![screen shot 2018-07-12 at 8 11 53 pm](https://user-images.githubusercontent.com/5572598/42664422-096c5ca2-8611-11e8-8de2-aaa4edd6e7d1.png)
