### ISSUE TITLE
Etherpad bugs when trying to work on new proposal 

### ISSUE THREAD

**Issue by LucileMP** [socialappslab/appcivist#3]
![etherpad issue 2](https://cloud.githubusercontent.com/assets/28006117/25425697/08b8d570-2a6d-11e7-83a4-beb601a53cd8.jpg)

**Comment by cdparra** [comment]
@LucileMP the problem has to do with the link that the system is creating for Working Groups in the sidebar. This link should contain the information of the campaign. Instead, due to some bug we will investigate and fix in this other [development issue](https://github.com/socialappslab/appcivist-pb-client/issues/607). Now that we know where the issue is, this should be fixed over the weekend. In the meantime, below is a how you can circumvent the issue while we fix it: 

1. When you visit a campaign, make note of the number that appears at the end of the url (in the example below is 202) 
![image](https://cloud.githubusercontent.com/assets/630150/25467265/1cd8c39e-2adb-11e7-8863-3fa31d6c0049.png)
2. When you click on a WG of that campaign, notice that the URL will look something as follow
`https://pb.appcivist.org/#/v2/assembly/110/campaign/0/group/234` with a `0` after the word `campaign/`. Replace that 0 with the number you saved before (e.g., 202) and reload the page of the group => `https://pb.appcivist.org/#/v2/assembly/110/campaign/202/group/234`
3. Visit any proposal. It should now load the etherpad text correctly.

**Comment by cdparra** [comment]
@LucileMP this should be fixed now. Please try, confirm and close the issue if everything works as expected.

**Comment by LucileMP** [comment]
Working ! Thanks
