### ISSUE TITLE
Change motivational prompts

### ISSUE THREAD

**Issue by jamesholston** [socialappslab/appcivist#30]
Update motivational prompts using new text and translations from

https://docs.google.com/spreadsheets/d/1PNUZIM5JMkCUtqrvqfu6zB8XWKb0xyCI7GIM5BH5snM/edit?usp=sharing

The ones we eliminated have to do with linking ideas to proposals.  We are not sure how this will be done in Phase 1, if at all.  In Phase 3, we will need to show the T2s that were grouped to form T3s.  But the Intercampus Assembly does the grouping.  So at this point, we are not sure that these linking prompts are relevant.

**Comment by cdparra** [comment]
DONE. Some notes: 
1. I've removed contributing messages from campaign page, but must leave them in proposal page for Vallejo's use. 
2. Message was replaced with a more simple version, because it was misunderstood. The email part was supposed to be an example, not the message itself. 
3. All other portuguese translations were integrated
