### ISSUE TITLE
Make Portuguese the default language for all Unifesp users

### ISSUE THREAD

**Issue by jamesholston** [socialappslab/appcivist#54]
Make Portuguese the default language for all users of the Unifesp site.  Regardless of last language used, the language upon login should be Portuguese.

**Comment by cdparra** [comment]
I am not sure I understand this: for not logged in users, the default language is already that of the specific campaign (which in this case is portuguese). For logged in users, we used their profile's language. Do you want us to overlook this and use the campaign's or assembly's language?. I don't reccommend this. 

Not using the language on the user's profile would require a change that is too costly, for the benefit of only handful of users of Unifesp assembly who have associated english as their profile language. 

cc @jamesholston @Alissonor

**Comment by cdparra** [comment]
I have added the label `under review` because we need some clarifications cc @jamesholston @Alissonor

**Comment by Alissonor** [comment]
Ok Cristian,

I’m sorry, I just don’t know how I did it, I don’t remember, but if it is a problem just with my profile, maybe because I have changed it without wanting, then I think we don’t need to care about.
Tks

[Enviada via celular]

Em 2 de abr de 2018, à(s) 19:24, Cristhian Parra <notifications@github.com<mailto:notifications@github.com>> escreveu:


Just in case, I checked and the only UNIFESP user who had a language setting different than Portuguese was rigitano... Updated to portuguese. Can you please try now and see if the add idea form correclty loads the portuguese version? @jamesholston<https://github.com/jamesholston> @Alissonor<https://github.com/Alissonor>

**Comment by cdparra** [comment]
Ok, I understand now. It was only a problem with one profile then. It might be that when the password was updated, the language was inadvertedly changed. Please, could you test this later? Change your password without changing anything else? If you experience the same issue of changing languages, then there is but in the password updating process, which would need a new issue created address that. 

I am closing this now. @Alissonor

**Comment by jamesholston** [comment]
Cristhian:  you say "we used their profile's language."  But I don't see how to set the language in profile.  I suggested that we add this feature in issue#xx.  I agree that (1) the default language for not logged in users is that of the campaign (in this case Portuguese) and (2) the user's profile language should trump the default if it is set to another language.  For example, my profile is set to English, so my account in unifesp site opens in English.  I can change it to Portuguese.  That is fine.  But where and how does a user set their profile language?
