### ISSUE TITLE
Change landing page to Campaign Page

### ISSUE THREAD

**Issue by jamesholston** [socialappslab/appcivist#68]
Change landing page to Campaign Page.  Currently it is Assembly Page.

**Comment by cdparra** [comment]
@jamesholston  Currently, this is the how domains are configured: 

`unifesp.appcivist.org` redirects to `Unifesp Assembly Page`
`ppi-unifesp.appcivist.org` redirects to `Unifesp PPI campaign page`. 

Are you asking to change this so that `unifesp.appcivist.org` also redirects to the same page? Or should we simply remove that domain?. If what you want is simply visiting directly the campaign page, then all you need to do is promote the right link and ignore the other link (or we can remove it). 

When you log in from any of these pages, it should then take you to the same page, but with all the buttons for logged in members available. 

Is it waht

**Comment by cdparra** [comment]
This is done now.
