### ISSUE TITLE
When we put a name of author that was already in the list, we have this bug, see bellow (it has a error message, but the author disappears of authors list) see below:

### ISSUE THREAD

**Issue by Alissonor** [socialappslab/appcivist#92]
When we put a name of author that was already in the list, we have this bug, see bellow (it has a error message, but the author disappears of authors list) see below:
![bug3](https://user-images.githubusercontent.com/37881481/39925488-45e1fbe6-5502-11e8-86d0-74ffaee36ae9.gif)

**Comment by cdparra** [comment]
@gvescu this is related to the way we treat non-logged in URLs (with uuids) and logged-in urls (with numerical ids). Make sure to modify the controllers of the campaign dashboard, contribution page and the working group page, so that if there's a Logged in USER, the backend endpoints we use use the corresopnding UUIDs instead of trying to find numerical ids that are not available in the URL. 

In other words: let's always use the ids in the UI route for the endpoints, and depending on whether they are UUIDs or IDs we decide if we query the public (starting with "/public") or private api endpoint. Now, we make that decision based on the existence or not of a user in ourl ocal storage.

**Comment by cdparra** [comment]
@gvescu ignore my previous comment, it is connected to the other issue. For this one, we just need to filter our the current authors from the list of members available to add.
