### ISSUE TITLE
When I´m logged in, and close the web navigator, and open it again in a new window, the site presents a bug, see below:

### ISSUE THREAD

**Issue by Alissonor** [socialappslab/appcivist#93]
When I´m logged in, and close the web navigator, and open it again in a new window, the site presents a bug, see below:
![bug4](https://user-images.githubusercontent.com/37881481/39925535-6f4b7584-5502-11e8-9a9f-e8dbce417810.gif)

**Comment by cdparra** [comment]
@gvescu this is related to the way we treat non-logged in URLs (with uuids) and logged-in urls (with numerical ids). Make sure to modify the controllers of the campaign dashboard, contribution page and the working group page, so that if there's a Logged in USER, the backend endpoints we use use the corresopnding UUIDs instead of trying to find numerical ids that are not available in the URL. 

In other words: let's always use the ids in the UI route for the endpoints, and depending on whether they are UUIDs or IDs we decide if we query the public (starting with "/public") or private api endpoint. Now, we make that decision based on the existence or not of a user in ourl ocal storage.
